### ISSUE TITLE
Time to event

### ISSUE THREAD

**Issue by Mushtaqml** [mkazmier/torchmtlr#2]
Hi, 

How can I use torchmtlr to calculate the time to event from mtlr_risk or mtlr_survival. Kindly can you assist in understanding it. 

Thanks

**Comment by mkazmier** [comment]
MTLR predicts an entire individual survival curve for each patient, so you don't really get a time-to-event prediction per se, just a probability that the event occurs within each time bin. One way to get a time-to-event prediction would be to select  some probability threshold (e.g. based on sensitivity/specificity) and use the first timepoint where the predicted probability of event is ≥ the threshold. A few other approaches are described in section 4.3 of [the original MTLR paper](https://proceedings.neurips.cc/paper/2011/hash/1019c8091693ef5c5f55970346633f92-Abstract.html).
